name: Add Issues to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/jjgroenendijk/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
