name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  copilot-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Request Copilot Review
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            
            // Add a comment requesting manual Copilot review
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: `🤖 **AI Review Requested**\n\nUse GitHub Copilot to review this PR:\n- Open the PR in VS Code\n- Use Copilot Chat: @workspace review this pull request\n- Or use the GitHub CLI: gh copilot review\n\nFor automated reviews, GitHub Copilot can be configured to review PRs automatically in repository settings.`
            });
            
            console.log('AI review reminder posted');
