name: Auto-close Issues on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  close-linked-issues:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
    
    steps:
      - name: Close linked issues
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body || '';
            
            // GitHub automatically closes issues with keywords like "closes #123"
            // This workflow adds a comment to confirm the closure
            const closesRegex = /(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+#(\d+)/gi;
            const closingIssues = [];
            
            let match;
            while ((match = closesRegex.exec(body)) !== null) {
              closingIssues.push(match[1]);
            }
            
            for (const issueNumber of closingIssues) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: parseInt(issueNumber),
                body: `✅ Closed by PR #${pr.number}`
              });
              
              console.log(`Added closure comment to issue #${issueNumber}`);
            }
