name: Link PRs to Issues

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  link-issues:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    
    steps:
      - name: Link PR to Issues
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body || '';
            const title = pr.title || '';
            
            // Find issue references in PR body and title
            const issueRegex = /#(\d+)/g;
            const closesRegex = /(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+#(\d+)/gi;
            
            const allIssues = new Set();
            const closingIssues = new Set();
            
            // Find all issue references
            let match;
            while ((match = issueRegex.exec(body + ' ' + title)) !== null) {
              allIssues.add(match[1]);
            }
            
            // Find issues that will be closed
            while ((match = closesRegex.exec(body)) !== null) {
              closingIssues.add(match[1]);
            }
            
            // Add comment to PR summarizing linked issues
            if (allIssues.size > 0) {
              const issueList = Array.from(allIssues).map(num => `#${num}`).join(', ');
              const closingList = Array.from(closingIssues);
              
              let comment = `### Linked Issues\n\n`;
              comment += `This PR references: ${issueList}\n\n`;
              
              if (closingList.length > 0) {
                const closingText = closingList.map(num => `#${num}`).join(', ');
                comment += `✅ Will close: ${closingText} when merged\n`;
              }
              
              console.log(`Found ${allIssues.size} linked issue(s)`);
            }
