name: Sync Labels with Project

on:
  issues:
    types: [labeled, unlabeled]
  pull_request:
    types: [labeled, unlabeled]

jobs:
  sync-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Update project based on labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          script: |
            const item = context.payload.issue || context.payload.pull_request;
            const labels = item.labels.map(l => l.name);
            
            console.log(`Processing ${item.number} with labels: ${labels.join(', ')}`);
            
            // Priority mapping
            if (labels.includes('priority: high')) {
              console.log('High priority item detected');
            }
            
            // Phase tracking
            if (labels.some(l => l.startsWith('phase:'))) {
              const phase = labels.find(l => l.startsWith('phase:'));
              console.log(`Item belongs to ${phase}`);
            }
            
            // Area categorization
            const areas = labels.filter(l => l.startsWith('area:'));
            if (areas.length > 0) {
              console.log(`Areas: ${areas.join(', ')}`);
            }
